services:
  backend:
    container_name: heart-monitor-backend
    network_mode: "host" 
    environment:
      - PYTHONUNBUFFERED=1
    image: ghcr.io/zawarudo87/home_wearable_heart_disease_monitoring_device:latest
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data:/app/backend/data
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    networks:
      - heart-monitor-network
    ports:
      - "9000:9000"
      - "9443:9443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  heart-monitor-network:
    driver: bridge

volumes:
  portainer_data: