services:
  backend:
    container_name: heart-monitor-backend
    environment:
      - PYTHONUNBUFFERED=1
      - ESP32_CANDIDATES=heart-monitor-esp32.local,host.docker.internal
    image: ghcr.io/zawarudo87/home_wearable_heart_disease_monitoring_device:latest
    networks:
      - heart-monitor-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "39244:39244"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data:/app/backend/data

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    networks:
      - heart-monitor-network
    ports:
      - "9000:9000"
      - "9443:9443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  heart-monitor-network:
    driver: bridge

volumes:
  portainer_data:
